#!/usr/bin/env node

/**
 * Local build script - reads .env file and generates env-local.js
 * Use this for local development instead of build.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read .env file
function loadEnvFile() {
  const envPath = path.join(__dirname, '.env');
  
  if (!fs.existsSync(envPath)) {
    console.error('❌ .env file not found!');
    console.log('Please create a .env file with your Firebase configuration.');
    process.exit(1);
  }

  const envContent = fs.readFileSync(envPath, 'utf8');
  const env = {};
  
  envContent.split('\n').forEach(line => {
    line = line.trim();
    // Skip comments and empty lines
    if (!line || line.startsWith('#')) return;
    
    const [key, ...valueParts] = line.split('=');
    const value = valueParts.join('=').trim();
    
    if (key && value) {
      env[key.trim()] = value;
    }
  });
  
  return env;
}

console.log('🔧 Starting local build process...\n');

// Load environment variables
const env = loadEnvFile();

console.log('✓ Loaded .env file');
console.log(`✓ Firebase Project ID: ${env.VITE_FIREBASE_PROJECT_ID || 'NOT SET'}\n`);

// Check if required Firebase variables are set
const requiredVars = [
  'VITE_FIREBASE_API_KEY',
  'VITE_FIREBASE_AUTH_DOMAIN',
  'VITE_FIREBASE_PROJECT_ID',
  'VITE_FIREBASE_STORAGE_BUCKET',
  'VITE_FIREBASE_MESSAGING_SENDER_ID',
  'VITE_FIREBASE_APP_ID'
];

const missingVars = requiredVars.filter(key => !env[key] || env[key].includes('your_'));

if (missingVars.length > 0) {
  console.error('❌ Missing or incomplete Firebase configuration:');
  missingVars.forEach(key => console.error(`   - ${key}`));
  console.log('\nPlease update your .env file with actual Firebase values.');
  console.log('Get them from: https://console.firebase.google.com/\n');
  process.exit(1);
}

// Create env-local.js file content
const envLocalContent = `// Local development environment configuration
// This file is AUTO-GENERATED by build-local.js from your .env file
// DO NOT commit this file to git (it's in .gitignore)
// DO NOT edit this file manually - edit .env instead and run build-local.js again

window.__ENV__ = {
  VITE_FIREBASE_API_KEY: '${env.VITE_FIREBASE_API_KEY}',
  VITE_FIREBASE_AUTH_DOMAIN: '${env.VITE_FIREBASE_AUTH_DOMAIN}',
  VITE_FIREBASE_PROJECT_ID: '${env.VITE_FIREBASE_PROJECT_ID}',
  VITE_FIREBASE_STORAGE_BUCKET: '${env.VITE_FIREBASE_STORAGE_BUCKET}',
  VITE_FIREBASE_MESSAGING_SENDER_ID: '${env.VITE_FIREBASE_MESSAGING_SENDER_ID}',
  VITE_FIREBASE_APP_ID: '${env.VITE_FIREBASE_APP_ID}'
};

console.log('[ENV-LOCAL] Local environment configuration loaded');
console.log('[ENV-LOCAL] Project ID:', window.__ENV__.VITE_FIREBASE_PROJECT_ID);
`;

// Write env-local.js file
const envLocalPath = path.join(__dirname, 'assets', 'js', 'config', 'env-local.js');
fs.writeFileSync(envLocalPath, envLocalContent, 'utf8');

console.log('✅ Generated assets/js/config/env-local.js');
console.log('   This file contains your Firebase configuration');
console.log('   It is gitignored and will NOT be committed\n');

console.log('📝 Next steps:');
console.log('   1. Add this script tag to your HTML files (in <head>):');
console.log('      <script src="assets/js/config/env-local.js"></script>');
console.log('   2. Start your local server: python -m http.server 8000');
console.log('   3. Visit: http://localhost:8000\n');

console.log('🚀 For production (Vercel), use the regular build.js script');
console.log('   which reads from environment variables instead.\n');

